Add some logging and write build.log file

diff --git a/apache2/configure b/apache2/configure
--- a/apache2/configure
+++ b/apache2/configure
@@ -12,6 +12,12 @@ EOF
 getProperties() {
     local APACHE_VERSION=$(getLatestVersion)
 
+    if [ -z "$APACHE_VERSION" ]; then
+        echo 'failed to lookup apache version' >&2
+
+        exit 1
+    fi
+
     local VERSION=$( \
         echo "$APACHE_VERSION" \
           | sed -E 's/^([0-9]+:)?([0-9]+\.[0-9]+(\.[0-9]+)?)(-([0-9]+))?.*/\2-r\5/' \
diff --git a/nodejs/configure b/nodejs/configure
--- a/nodejs/configure
+++ b/nodejs/configure
@@ -2,7 +2,17 @@
 
 FROM=$(sed -n -E "s/^FROM ([^# ]+).*/\1/p" Dockerfile)
 
+parseBuildVersions() {
+    if yq --help | grep -q kislyuk; then
+        yq -r '.build.versions[]' "$1"
+    else
+        yq r "$1" 'build.versions[*]'
+    fi
+}
+
 getLatestVersion() {
+    echo 'getting latest nodejs release for $1 ...' >&2
+
     docker run -i --rm \
         --user root \
         --entrypoint=/bin/sh \
@@ -16,7 +26,15 @@ getLatestVersion() {
 EOF
 }
 
-for v in $(yq r build.yml build.versions[*] | sed -E 's/^ *- |"//g'); do
+versions=$(parseBuildVersions 'build.yml' | sed -E 's/^ *- |"//g')
+
+if [ -z "$versions" ]; then
+    echo 'failed to parse build.yml' >&2
+
+    exit 255
+fi
+
+for v in $versions; do
     nodejs_version=$(getLatestVersion "$v")
     nodejs_major_version=$v
     version=$( \
@@ -24,6 +42,12 @@ for v in $(yq r build.yml build.versions[*] | sed -E 's/^ *- |"//g'); do
             | sed -E 's/^([0-9]+:)?([0-9]+(\.[0-9]+)*)(-([0-9]+))?.*/\2-r\5/' \
             | sed -E 's/-r$//' \
       )
+
+    if [ -z "$version" ]; then
+        echo "failed to determine version from $nodejs_version" >&2
+
+        exit 255
+    fi
 
     {
       echo "NODEJS_VERSION=$nodejs_version"
diff --git a/php/configure b/php/configure
--- a/php/configure
+++ b/php/configure
@@ -2,11 +2,29 @@
 
 FROM=andrewmackrodt/$(basename "$(pwd)")
 
+parseBuildVersions() {
+    if yq --help | grep -q kislyuk; then
+        yq -r '.build.versions[]' "$1"
+    else
+        yq r "$1" 'build.versions[*]'
+    fi
+}
+
 getLatestVersions() {
+    local versions=$(parseBuildVersions 'build.yml' | sed -E 's/^ *- |"//g')
+
+    if [ -z "$versions" ]; then
+        echo 'failed to parse build.yml' >&2
+
+        exit 255
+    fi
+
+    echo 'getting latest php versions ...' >&2
+
     docker run -i --rm \
         --user root \
         --entrypoint=/bin/sh \
-        -e "versions=$(yq r build.yml build.versions[*] | sed -E 's/^ *- |"//g')" \
+        -e "versions=$versions" \
         "$FROM" <<'EOF'
             apt-get update -qq
             for v in $versions; do
@@ -21,7 +39,13 @@ getLatestVersions() {
 EOF
 }
 
-for v in $(getLatestVersions); do
+versions=$(getLatestVersions)
+
+if [ -z "$versions" ]; then
+    exit 255
+fi
+
+for v in $versions; do
     php_version=$(echo "$v" | cut -f1 -d':')
     version=$(echo "$v" | cut -f2 -d':')
 
